### ISSUE TITLE
Labels break highlighting

### ISSUE THREAD

**Issue by HendrikJanssen** [murtaza64/tree-sitter-groovy#13]
One of our uses of Groovy is the execution of Spock tests. Spock is a test framework, which makes [extensive use of labels](https://spockframework.org/spock/docs/1.0/spock_primer.html#_blocks) to mark the sections of a test. Example:

```groovy
class Test {
	def "test add"() {
		when:
		def a = 10
		def b = 10
		def result = a + b

		then:
		result == 20
	}
}
```

Labels are kind of "inherited" from [Java](https://docs.oracle.com/javase/specs/jls/se7/html/jls-14.html#jls-14.7). With the current parser, they seem to be missing/broken.
Highlighting for the example in my neovim (Note the broken `def` highlighting in the line right after the first label):

<img width="352" alt="Bildschirmfoto 2024-07-17 um 14 47 30" src="https://github.com/user-attachments/assets/a144628c-48b5-4e92-bf32-d70010f23345">

In bigger files, the highlighting is all over the place.

I tried to locate label parsing in your grammar.js and could not find it, but admittedly, I am not a treesitter expert. Can you verify that labels are simply missing? If they are missing, I might give their implementation a try.

**Comment by murtaza64** [comment]
I'm pretty sure I didn't implement labels (I didn't know they existed lol). Feel free to give the implementation a shot!
