### ISSUE TITLE
Fails to parse map keys as strings

### ISSUE THREAD

**Issue by fussybeaver** [murtaza64/tree-sitter-groovy#17]
Thank you for this treesitter library!

I'm having trouble with this groovy syntax:

```groovy
def str_key = ["hello": false]
```

It seems to parse into this AST:

```
(declaration
        name: (identifier)
        value: (list
          (string
            (string_content))
          (ERROR)))
```

I'm having a poke around, but not too familiar this project yet...

**Comment by murtaza64** [comment]
thanks for reporting! if you have any luck fixing this, I'm happy to merge any PRs. probably won't have time to look myself for the next few days
