### ISSUE TITLE
More than one annotation on a class/function not understood by parser

### ISSUE THREAD

**Issue by jonathan-elize** [murtaza64/tree-sitter-groovy#23]
Firstly, thank you for taking out the time to make this!

I noticed that if there's more than one annotation on a Class or a function that it won't be picked up correctly resulting in an error:

<img width="1326" alt="Screenshot 2024-10-30 at 12 42 17 AM" src="https://github.com/user-attachments/assets/e490d6fe-016a-419f-8e8b-e59241259b3b">

Can a fix be made for this?

**Comment by murtaza64** [comment]
Fixed in https://github.com/murtaza64/tree-sitter-groovy/commit/b53a8cc1075e056b8223b86f3bb392e0d57ae101
