### ISSUE TITLE
Backslash in regex breaks highlighting (nvim-treesitter)

### ISSUE THREAD

**Issue by mitchdost** [murtaza64/tree-sitter-groovy#7]
Hi,

I am using nvim 0.9.5 and nvim-treesitter c06292f and current tree-sitter-groovy.

After the first backslash inside a regular expression the rest of the code until the last line is recognized as a string.

This breaks nvim-treesitter syntax highlighting.

If I remove the backslashes, the highlighting works again.

```groovy
def String getTomcatPort(String name) {
    // name is s/th like tomcat1
    if (name && name.find(/\d+/)) {
        def num = name.find(/\d+/) as int
        return (8100 + num).toString()
    }
    return ""
}

pipeline {
    agent any
}
```

Regards
Mitch

**Comment by murtaza64** [comment]
Thanks for raising this, looking into it!

**Comment by murtaza64** [comment]
I think I've fixed it in https://github.com/murtaza64/tree-sitter-groovy/commit/3c25d1ce6c1eb9da34215060372792dc9f439b0c. Update should automatically propagate downstream soon, but let me know if it's still broken in a few days

**Comment by mitchdost** [comment]
Cool, thank you for your effort! I will give you a feedback.

**Comment by mitchdost** [comment]
Hi,
I can confirm, that your fix worked for me with the new version of the groovy treesitter parser.
Thank you again!
